CREATE DATABASE IF NOT EXISTS meil_esg
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_0900_ai_ci;
USE meil_esg;

CREATE TABLE IF NOT EXISTS projects (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(120) NOT NULL,
  code VARCHAR(30) NOT NULL UNIQUE,
  description VARCHAR(500) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS users (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(120) NOT NULL,
  email VARCHAR(190) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  role ENUM('PROJECT_USER', 'REVIEWER', 'ADMIN') NOT NULL,
  project_id INT UNSIGNED NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT fk_users_project FOREIGN KEY (project_id) REFERENCES projects (id) ON UPDATE CASCADE ON DELETE SET NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS submissions (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  project_id INT UNSIGNED NOT NULL,
  reporting_year SMALLINT UNSIGNED NOT NULL,
  category VARCHAR(40) NOT NULL DEFAULT 'ENVIRONMENTAL',
  sub_category VARCHAR(40) NOT NULL DEFAULT 'ENERGY',
  energy_value DECIMAL(18, 3) NOT NULL,
  unit ENUM('kWh', 'MWh') NOT NULL DEFAULT 'kWh',
  description VARCHAR(1000) NOT NULL,
  evidence_file_name VARCHAR(255) NULL,
  evidence_file_url VARCHAR(500) NULL,
  status ENUM('PENDING', 'UNDER_REVIEW', 'CORRECTION_REQUIRED', 'APPROVED') NOT NULL DEFAULT 'PENDING',
  submitted_by INT UNSIGNED NOT NULL,
  review_comment VARCHAR(1000) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  INDEX idx_submissions_project_year (project_id, reporting_year),
  INDEX idx_submissions_status_year (status, reporting_year),
  CONSTRAINT fk_submissions_project FOREIGN KEY (project_id) REFERENCES projects (id) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_submissions_user FOREIGN KEY (submitted_by) REFERENCES users (id) ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS submission_reviews (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  submission_id INT UNSIGNED NOT NULL,
  reviewer_id INT UNSIGNED NOT NULL,
  decision ENUM('UNDER_REVIEW', 'CORRECTION_REQUIRED', 'APPROVED') NOT NULL,
  comment VARCHAR(1000) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  INDEX idx_submission_reviews_submission (submission_id),
  CONSTRAINT fk_reviews_submission FOREIGN KEY (submission_id) REFERENCES submissions (id) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT fk_reviews_user FOREIGN KEY (reviewer_id) REFERENCES users (id) ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS submission_history (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  submission_id INT UNSIGNED NOT NULL,
  status ENUM('PENDING', 'UNDER_REVIEW', 'CORRECTION_REQUIRED', 'APPROVED') NOT NULL,
  comment VARCHAR(1000) NULL,
  changed_by INT UNSIGNED NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  INDEX idx_submission_history_submission (submission_id, created_at),
  CONSTRAINT fk_history_submission FOREIGN KEY (submission_id) REFERENCES submissions (id) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT fk_history_user FOREIGN KEY (changed_by) REFERENCES users (id) ON UPDATE CASCADE ON DELETE SET NULL
) ENGINE=InnoDB;
